host: 127.0.0.1
port: 4004
#url: "https://www.keboola.com"
url: "https://confident-lovelace-ce6a6c.netlify.com"
permalink: :title
future: true
highlighter: true
exclude: ['Rakefile.rb', 'CNAME', 'README.md', 'config.codekit3', 'Gemfile*', 'less', 'js/global.js']
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  title: ' - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
   product:
     output: true
     permalink: /:collection/:path/
   platform:
     output: true
     permalink: /:collection/:path/
   solutions:
     output: true
     permalink: /:collection/:path/
   learning:
     output: true
     permalink: /:collection/:path/
   customer-stories:
     output: true
     permalink: /:collection/:path/
   whitepapers:
     output: true
     permalink: /:collection/:path/
   events:
     output: true
     permalink: /:collection/:path/
   webinars:
     output: true
     permalink: /:collection/:path/
   about:
     output: true
     permalink: /:collection/:path/
