host: 127.0.0.1
port: 4004
url: "https://www.keboola.com"
permalink: none
highlighter: true
exclude: ['Rakefile.rb', 'CNAME', 'README.md', 'config.codekit3', 'Gemfile*', 'less']
plugins:
  - jekyll-sitemap

collections:
   product:
     output: true
     permalink: /:collection/:path/
   solutions:
     output: true
     permalink: /:collection/:path/
