---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page-builder
- type: directory
  path: _product
  label: Product
  create: all
  match: "**/*"
- type: directory
  path: _platform
  label: Platform
  create: all
  match: "**/*"
  templates:
  - page-builder
- type: directory
  path: _solutions
  label: Solutions
  create: all
  match: "**/*"
  templates:
  - page-builder
- type: directory
  path: _learning
  label: Learning
  create: all
  match: "**/*"
  templates:
  - page-builder
- type: directory
  path: _about
  label: About
  create: all
  match: "**/*"
  templates:
  - page-builder
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
