---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - text-page
  - page-builder
  - contact-form
- type: directory
  path: _product
  label: Product
  create: all
  match: "**/*"
- type: directory
  path: _platform
  label: Platform
  create: all
  match: "**/*"
  templates:
  - page-builder
- type: directory
  path: _solutions
  label: Solutions
  create: all
  match: "**/*"
  templates:
  - page-builder
- type: directory
  path: _customer-stories
  label: Customer stories
  create: documents
  match: "**/*"
  templates:
  - post-case-study
- type: directory
  path: _whitepapers
  label: Whitepapers
  create: documents
  match: "**/*"
  templates:
  - post-case-study
- type: directory
  path: _events
  label: Events
  create: documents
  match: "**/*"
  templates:
  - post-events
- type: directory
  path: _webinars
  label: Webinars
  create: documents
  match: "**/*"
  templates:
  - post-events
- type: directory
  path: _about
  label: About
  create: all
  match: "**/*"
  templates:
  - page-builder
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
